version: '3.8'

services:
  frontend:
    image: raymi-image
    container_name: host-raymi-frontend
    build:
      context: ./frontend
      dockerfile: ../config/frontend/prod/Dockerfile
    ports:
      - ${NEXT_PUBLIC_APP_PORT}:3000
    depends_on:
      - backend
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - .env

  backend:
    image: raymi-image
    container_name: host-raymi-backend
    build:
      context: ./backend
      dockerfile: ../config/backend/prod/Dockerfile
    ports:
      - ${NODE_PORT_SERVER}:3000
    restart: always
    depends_on:
      - database
    stdin_open: true
    tty: true
    env_file:
      - .env

  database:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
